// ✅ SHOPEZ COMPLETE PRODUCT DATABASE - 56 Products with Real Images

const products = [
  // ==================== ELECTRONICS (8 Products) ====================
  {
    id: 1,
    name: "Wireless Earbuds Pro",
    category: "Electronics",
    price: 4999,
    originalPrice: 7999,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQorIFUxaChpcQYueyMCRQ9xlU3x-DGVbfmyQ&s",
    description: "Premium wireless earbuds with noise cancellation, 30-hour battery life, and crystal-clear sound quality.",
    rating: 4.8,
    reviews: 324,
    inStock: true,
    quantity: 15
  },
  {
    id: 2,
    name: "Smartphone X12",
    category: "Electronics",
    price: 29999,
    originalPrice: 39999,
    image: "https://images.samsung.com/is/image/samsung/assets/in/s2602/pcd/audio-sound/PF_Main-Category_Galaxy-Smartphone_176x176.png?$ORIGIN_PNG$",
    description: "Latest smartphone with 5G, 48MP camera, AMOLED display, and powerful processor.",
    rating: 4.9,
    reviews: 512,
    inStock: true,
    quantity: 8
  },
  {
    id: 3,
    name: "Smart Watch Ultra",
    category: "Electronics",
    price: 12999,
    originalPrice: 18999,
    image: "https://www.fastrack.in/dw/image/v2/BKDD_PRD/on/demandware.static/-/Sites-titan-master-catalog/default/dw803d2a14/images/Fastrack/Catalog/38149WM01_1.jpg?sw=600&sh=600",
    description: "Advanced fitness tracking, heart rate monitor, sleep tracking, and 7-day battery life.",
    rating: 4.7,
    reviews: 285,
    inStock: true,
    quantity: 12
  },
  {
    id: 4,
    name: "Laptop Pro 15",
    category: "Electronics",
    price: 79999,
    originalPrice: 99999,
    image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=500&h=500&fit=crop",
    description: "High-performance laptop with Intel i7, 16GB RAM, 512GB SSD, perfect for professionals.",
    rating: 4.9,
    reviews: 198,
    inStock: true,
    quantity: 5
  },
  {
    id: 5,
    name: "Wireless Mouse",
    category: "Electronics",
    price: 1299,
    originalPrice: 1999,
    image: "https://images.unsplash.com/photo-1527814050087-3793815479db?w=500&h=500&fit=crop",
    description: "Ergonomic wireless mouse with precision tracking, long battery life.",
    rating: 4.6,
    reviews: 156,
    inStock: true,
    quantity: 25
  },
  {
    id: 6,
    name: "USB-C Fast Charger",
    category: "Electronics",
    price: 899,
    originalPrice: 1299,
    image: "https://images.unsplash.com/photo-1625948515291-69613efd103f?w=500&h=500&fit=crop",
    description: "Super-fast 65W USB-C charger, compatible with all devices.",
    rating: 4.8,
    reviews: 412,
    inStock: true,
    quantity: 30
  },
  {
    id: 7,
    name: "Portable Speaker",
    category: "Electronics",
    price: 3499,
    originalPrice: 5999,
    image: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=500&h=500&fit=crop",
    description: "Waterproof Bluetooth speaker with 360° sound and 20-hour battery.",
    rating: 4.7,
    reviews: 267,
    inStock: true,
    quantity: 18
  },
  {
    id: 8,
    name: "Webcam 4K",
    category: "Electronics",
    price: 5999,
    originalPrice: 8999,
    image: "https://images.unsplash.com/photo-1598556261222-7f100c0e16b8?w=500&h=500&fit=crop",
    description: "Professional 4K webcam with auto-focus and built-in microphone.",
    rating: 4.8,
    reviews: 189,
    inStock: true,
    quantity: 14
  },

  // ==================== FASHION (8 Products) ====================
  {
    id: 9,
    name: "Summer Dress Collection",
    category: "Fashion",
    price: 1999,
    originalPrice: 3499,
    image: "https://images.unsplash.com/photo-1595777712802-46a82f49d3e7?w=500&h=500&fit=crop",
    description: "Beautiful summer dress with comfortable fabric, perfect for all occasions.",
    rating: 4.7,
    reviews: 342,
    inStock: true,
    quantity: 40
  },
  {
    id: 10,
    name: "Denim Jacket",
    category: "Fashion",
    price: 2499,
    originalPrice: 3999,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS4shkI9c9Twf0c3POugOmBdWIQmAIsELQ8qo2vb8lB9w&s=10",
    description: "Classic denim jacket, perfect for casual and formal wear.",
    rating: 4.6,
    reviews: 215,
    inStock: true,
    quantity: 22
  },
  {
    id: 11,
    name: "Elegant Saree",
    category: "Fashion",
    price: 4999,
    originalPrice: 7999,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTctz6ECn6KIIAZs_9eUfPkmKmF7D1SqU8bHOwM3c4A1g&s=10",
    description: "Traditional silk saree with beautiful embroidery and elegant design.",
    rating: 4.9,
    reviews: 289,
    inStock: true,
    quantity: 16
  },
  {
    id: 12,
    name: "Casual T-Shirt Bundle",
    category: "Fashion",
    price: 799,
    originalPrice: 1299,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRE8jfnWQOncL-wUjuIrN6AQNsUJfY70qIgEQUKt1aieA&s=10",
    description: "Pack of 3 premium cotton t-shirts in various colors.",
    rating: 4.5,
    reviews: 512,
    inStock: true,
    quantity: 50
  },
  {
    id: 13,
    name: "Cargo Pants",
    category: "Fashion",
    price: 2299,
    originalPrice: 3499,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRl5r_yNIfUyuQrKDW3-tbEOOvpXACMMKBxlH0DY9ZScA&s=10",
    description: "Comfortable cargo pants with multiple pockets, perfect for outdoor adventures.",
    rating: 4.6,
    reviews: 198,
    inStock: true,
    quantity: 28
  },
  {
    id: 14,
    name: "Leather Belt",
    category: "Fashion",
    price: 899,
    originalPrice: 1499,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ1prmtcZ4bpbNT6bEW_wyJy2_dsSAhlQ9k9dTxUxZdbA&s=10",
    description: "Premium leather belt with metal buckle, versatile and durable.",
    rating: 4.7,
    reviews: 156,
    inStock: true,
    quantity: 35
  },
  {
    id: 15,
    name: "Designer Blazer",
    category: "Fashion",
    price: 5999,
    originalPrice: 9999,
    image: "https://images.unsplash.com/photo-1539533057440-7bf6b1c3e2b9?w=500&h=500&fit=crop",
    description: "Professional blazer for office and formal occasions.",
    rating: 4.8,
    reviews: 267,
    inStock: true,
    quantity: 12
  },
  {
    id: 16,
    name: "Yoga Leggings",
    category: "Fashion",
    price: 1299,
    originalPrice: 2499,
    image: "https://images.unsplash.com/photo-1506629082632-11c7e44724af?w=500&h=500&fit=crop",
    description: "Comfortable high-waist yoga leggings with pockets and breathable fabric.",
    rating: 4.7,
    reviews: 445,
    inStock: true,
    quantity: 32
  },

  // ==================== BEAUTY (8 Products) ====================
  {
    id: 17,
    name: "Skincare Kit Deluxe",
    category: "Beauty",
    price: 2499,
    originalPrice: 4499,
    image: "https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=500&h=500&fit=crop",
    description: "Complete skincare routine with cleanser, toner, and moisturizer.",
    rating: 4.8,
    reviews: 523,
    inStock: true,
    quantity: 28
  },
  {
    id: 18,
    name: "Lipstick Collection",
    category: "Beauty",
    price: 999,
    originalPrice: 1699,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRpG3BVe7wgDt5pQ4VrPyOl9D5SZ09ItG2UH_San0wPNQ&s=10",
    description: "Set of 6 premium lipsticks in vibrant colors and matte finish.",
    rating: 4.7,
    reviews: 612,
    inStock: true,
    quantity: 35
  },
  {
    id: 19,
    name: "Foundation Pro",
    category: "Beauty",
    price: 1299,
    originalPrice: 1999,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRpPGMmsjghR38-qQlHCfMfexNfVBQNkfuKububoetfGg&s=10",
    description: "Full-coverage foundation with SPF 30, long-lasting formula.",
    rating: 4.8,
    reviews: 389,
    inStock: true,
    quantity: 22
  },
  {
    id: 20,
    name: "Hair Care Combo",
    category: "Beauty",
    price: 1799,
    originalPrice: 2999,
    image: "https://images.unsplash.com/photo-1585747860715-cd4628902d4a?w=500&h=500&fit=crop",
    description: "Shampoo and conditioner set for all hair types.",
    rating: 4.6,
    reviews: 267,
    inStock: true,
    quantity: 40
  },
  {
    id: 21,
    name: "Eye Shadow Palette",
    category: "Beauty",
    price: 899,
    originalPrice: 1499,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQAeSyjeHXdWlWUKjJzIQmNSvKZyf2YaKNJ4wm3FOpCpg&s=10",
    description: "12-color eyeshadow palette with pigmented colors.",
    rating: 4.7,
    reviews: 445,
    inStock: true,
    quantity: 26
  },
  {
    id: 22,
    name: "Face Mask Sheet",
    category: "Beauty",
    price: 299,
    originalPrice: 499,
    image: "https://images.unsplash.com/photo-1602084113235-7d440d0ce943?w=500&h=500&fit=crop",
    description: "Pack of 10 hydrating face masks for instant glow.",
    rating: 4.8,
    reviews: 623,
    inStock: true,
    quantity: 50
  },
  {
    id: 23,
    name: "Perfume Elegance",
    category: "Beauty",
    price: 2999,
    originalPrice: 4499,
    image: "https://images.unsplash.com/photo-1594643690529-abdea3fd68d1?w=500&h=500&fit=crop",
    description: "Premium perfume with long-lasting fragrance.",
    rating: 4.9,
    reviews: 334,
    inStock: true,
    quantity: 18
  },
  {
    id: 24,
    name: "Nail Polish Set",
    category: "Beauty",
    price: 699,
    originalPrice: 1199,
    image: "https://images.unsplash.com/photo-1604654894610-df63bc536371?w=500&h=500&fit=crop",
    description: "12 vibrant nail polish colors with quick-dry formula.",
    rating: 4.6,
    reviews: 512,
    inStock: true,
    quantity: 38
  },

  // ==================== HOME DECOR (8 Products) ====================
  {
    id: 25,
    name: "Decorative Pillow Set",
    category: "Home Decor",
    price: 1999,
    originalPrice: 3499,
    image: "https://images.unsplash.com/photo-1578500494198-246f612d03b3?w=500&h=500&fit=crop",
    description: "Set of 4 decorative pillows with beautiful patterns.",
    rating: 4.7,
    reviews: 267,
    inStock: true,
    quantity: 20
  },
  {
    id: 26,
    name: "Wall Art Canvas",
    category: "Home Decor",
    price: 2499,
    originalPrice: 3999,
    image: "https://images.unsplash.com/photo-1578500041491-cac6c40a0c72?w=500&h=500&fit=crop",
    description: "Modern canvas art prints for living room decoration.",
    rating: 4.8,
    reviews: 189,
    inStock: true,
    quantity: 15
  },
  {
    id: 27,
    name: "Table Lamp",
    category: "Home Decor",
    price: 1299,
    originalPrice: 1999,
    image: "https://images.unsplash.com/photo-1565636192335-14c0d3eea1e7?w=500&h=500&fit=crop",
    description: "Elegant table lamp with warm LED light and modern design.",
    rating: 4.6,
    reviews: 156,
    inStock: true,
    quantity: 18
  },
  {
    id: 28,
    name: "Curtain Panels",
    category: "Home Decor",
    price: 1799,
    originalPrice: 2999,
    image: "https://images.unsplash.com/photo-1579018118736-13947c03656f?w=500&h=500&fit=crop",
    description: "Beautiful blackout curtain panels for bedroom.",
    rating: 4.7,
    reviews: 223,
    inStock: true,
    quantity: 25
  },
  {
    id: 29,
    name: "Plant Pots Set",
    category: "Home Decor",
    price: 999,
    originalPrice: 1699,
    image: "https://images.unsplash.com/photo-1578909496179-bc9f51f48d16?w=500&h=500&fit=crop",
    description: "Set of 5 ceramic plant pots in different sizes.",
    rating: 4.5,
    reviews: 312,
    inStock: true,
    quantity: 30
  },
  {
    id: 30,
    name: "Mirror Wall Hanging",
    category: "Home Decor",
    price: 1499,
    originalPrice: 2499,
    image: "https://images.unsplash.com/photo-1595521014124-bf0827a08c96?w=500&h=500&fit=crop",
    description: "Decorative mirror with elegant frame.",
    rating: 4.6,
    reviews: 178,
    inStock: true,
    quantity: 16
  },
  {
    id: 31,
    name: "Door Mat",
    category: "Home Decor",
    price: 499,
    originalPrice: 899,
    image: "https://images.unsplash.com/photo-1533696635125-bfcb22466035?w=500&h=500&fit=crop",
    description: "Soft and durable welcome door mat.",
    rating: 4.7,
    reviews: 234,
    inStock: true,
    quantity: 35
  },
  {
    id: 32,
    name: "Desk Organizer",
    category: "Home Decor",
    price: 799,
    originalPrice: 1299,
    image: "https://images.unsplash.com/photo-1610701596007-11502861dcfa?w=500&h=500&fit=crop",
    description: "Wooden desk organizer for office space.",
    rating: 4.8,
    reviews: 267,
    inStock: true,
    quantity: 28
  },

  // ==================== FOOTWEAR (8 Products) ====================
  {
    id: 33,
    name: "Running Shoes Pro",
    category: "Footwear",
    price: 4999,
    originalPrice: 7999,
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500&h=500&fit=crop",
    description: "Professional running shoes with cushioning and support.",
    rating: 4.8,
    reviews: 445,
    inStock: true,
    quantity: 20
  },
  {
    id: 34,
    name: "Casual Sneakers",
    category: "Footwear",
    price: 2499,
    originalPrice: 3999,
    image: "https://images.unsplash.com/photo-1460353581641-37baddab0fa2?w=500&h=500&fit=crop",
    description: "Comfortable casual sneakers for everyday wear.",
    rating: 4.7,
    reviews: 523,
    inStock: true,
    quantity: 32
  },
  {
    id: 35,
    name: "Formal Heels",
    category: "Footwear",
    price: 2999,
    originalPrice: 4999,
    image: "https://images.unsplash.com/photo-1543163521-9efba06d3e3b?w=500&h=500&fit=crop",
    description: "Elegant formal heels perfect for special occasions.",
    rating: 4.9,
    reviews: 312,
    inStock: true,
    quantity: 15
  },
  {
    id: 36,
    name: "Flip Flops Comfort",
    category: "Footwear",
    price: 599,
    originalPrice: 999,
    image: "https://images.unsplash.com/photo-1459695639936-d89eb0baec52?w=500&h=500&fit=crop",
    description: "Comfortable flip flops for beach and casual wear.",
    rating: 4.6,
    reviews: 234,
    inStock: true,
    quantity: 40
  },
  {
    id: 37,
    name: "Hiking Boots",
    category: "Footwear",
    price: 5999,
    originalPrice: 8999,
    image: "https://images.unsplash.com/photo-1542221866-6851fccdd5b1?w=500&h=500&fit=crop",
    description: "Durable hiking boots for outdoor adventures.",
    rating: 4.8,
    reviews: 189,
    inStock: true,
    quantity: 12
  },
  {
    id: 38,
    name: "Ballet Flats",
    category: "Footwear",
    price: 1499,
    originalPrice: 2499,
    image: "https://images.unsplash.com/photo-1548062407-3826521014e6?w=500&h=500&fit=crop",
    description: "Elegant ballet flats for office and casual occasions.",
    rating: 4.7,
    reviews: 267,
    inStock: true,
    quantity: 24
  },
  {
    id: 39,
    name: "Sandals Casual",
    category: "Footwear",
    price: 899,
    originalPrice: 1499,
    image: "https://images.unsplash.com/photo-1535148566835-c5afc3de0308?w=500&h=500&fit=crop",
    description: "Comfortable casual sandals for everyday wear.",
    rating: 4.6,
    reviews: 345,
    inStock: true,
    quantity: 28
  },
  {
    id: 40,
    name: "Loafers Premium",
    category: "Footwear",
    price: 3499,
    originalPrice: 5499,
    image: "https://images.unsplash.com/photo-1546001291-5a367f310ff0?w=500&h=500&fit=crop",
    description: "Premium leather loafers for formal and casual wear.",
    rating: 4.8,
    reviews: 178,
    inStock: true,
    quantity: 16
  },

  // ==================== BOOKS (8 Products) ====================
  {
    id: 41,
    name: "Self-Help Bestseller",
    category: "Books",
    price: 299,
    originalPrice: 499,
    image: "https://images.unsplash.com/photo-1507842217343-583f20270319?w=500&h=500&fit=crop",
    description: "Inspiring self-help book for personal development.",
    rating: 4.8,
    reviews: 567,
    inStock: true,
    quantity: 50
  },
  {
    id: 42,
    name: "Fiction Novel",
    category: "Books",
    price: 349,
    originalPrice: 599,
    image: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=500&h=500&fit=crop",
    description: "Exciting fiction novel with engaging storyline.",
    rating: 4.7,
    reviews: 445,
    inStock: true,
    quantity: 35
  },
  {
    id: 43,
    name: "Coding Masterclass",
    category: "Books",
    price: 499,
    originalPrice: 799,
    image: "https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=500&h=500&fit=crop",
    description: "Complete guide to programming and software development.",
    rating: 4.9,
    reviews: 234,
    inStock: true,
    quantity: 28
  },
  {
    id: 44,
    name: "Business Strategy",
    category: "Books",
    price: 449,
    originalPrice: 699,
    image: "https://images.unsplash.com/photo-1524104218490-a1aae8fa4e5f?w=500&h=500&fit=crop",
    description: "Learn business strategies from industry experts.",
    rating: 4.7,
    reviews: 189,
    inStock: true,
    quantity: 22
  },
  {
    id: 45,
    name: "Cooking Recipes",
    category: "Books",
    price: 399,
    originalPrice: 599,
    image: "https://images.unsplash.com/photo-1507842217343-583f20270319?w=500&h=500&fit=crop",
    description: "Delicious recipes from around the world.",
    rating: 4.8,
    reviews: 312,
    inStock: true,
    quantity: 32
  },
  {
    id: 46,
    name: "History Chronicles",
    category: "Books",
    price: 349,
    originalPrice: 549,
    image: "https://images.unsplash.com/photo-1519052537793-e21dde1b8e74?w=500&h=500&fit=crop",
    description: "Fascinating historical events and stories.",
    rating: 4.6,
    reviews: 267,
    inStock: true,
    quantity: 26
  },
  {
    id: 47,
    name: "Psychology Insights",
    category: "Books",
    price: 429,
    originalPrice: 649,
    image: "https://images.unsplash.com/photo-1503446773353-c9a90f3a5b5d?w=500&h=500&fit=crop",
    description: "Understanding human behavior and psychology.",
    rating: 4.7,
    reviews: 178,
    inStock: true,
    quantity: 30
  },
  {
    id: 48,
    name: "Travel Guide",
    category: "Books",
    price: 379,
    originalPrice: 579,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTBbP6oS4j3wvJCTrZVtxOKCaNchiFuH5uEDSAzRk218w&s=10",
    description: "Complete travel guide to popular destinations.",
    rating: 4.8,
    reviews: 223,
    inStock: true,
    quantity: 28
  },

  // ==================== ACCESSORIES (8 Products) ====================
  {
    id: 49,
    name: "Sunglasses UV Protection",
    category: "Accessories",
    price: 1299,
    originalPrice: 1999,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ-7SrhdZjfnezrF3h9V--HUWE7gwlXdJpu0GCG-3WGHA&s=10",
    description: "Stylish sunglasses with 100% UV protection.",
    rating: 4.8,
    reviews: 345,
    inStock: true,
    quantity: 28
  },
  {
    id: 50,
    name: "Handbag Designer",
    category: "Accessories",
    price: 4999,
    originalPrice: 7999,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT60aO3bVpF77H76hhHnbaoQ5Hmsh4YAcGq1RoeaEgVkg&s=10",
    description: "Premium designer handbag with elegant style.",
    rating: 4.9,
    reviews: 267,
    inStock: true,
    quantity: 10
  },
  {
    id: 51,
    name: "Scarf Collection",
    category: "Accessories",
    price: 799,
    originalPrice: 1299,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRYDZT4cMsYUE9h279j9dV3joMXZvnJULBHPzeb5tKYaw&s=10",
    description: "Versatile scarves in various colors and patterns.",
    rating: 4.7,
    reviews: 234,
    inStock: true,
    quantity: 32
  },
  {
    id: 52,
    name: "Watch Elegant",
    category: "Accessories",
    price: 3999,
    originalPrice: 5999,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCZFjhE85NTYRCLgRMV8RZOcwCkJXlkRsN7D0XJDGlGg&s=10",
    description: "Elegant analog watch with leather strap.",
    rating: 4.8,
    reviews: 189,
    inStock: true,
    quantity: 15
  },
  {
    id: 53,
    name: "Jewelry Set",
    category: "Accessories",
    price: 2499,
    originalPrice: 3999,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQa86TQIRqf_KDQI32VcOZ_5VRzjWZJxsomPOVLevjR9Q&s=10",
    description: "Beautiful jewelry set for special occasions.",
    rating: 4.7,
    reviews: 312,
    inStock: true,
    quantity: 18
  },
  {
    id: 54,
    name: "Backpack Travel",
    category: "Accessories",
    price: 2299,
    originalPrice: 3499,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTh5CQ8MuBe4J3HNjNEfKRnddzzLcbWcnCNA1vdl5RURQ&s=10",
    description: "Durable travel backpack with multiple compartments.",
    rating: 4.6,
    reviews: 267,
    inStock: true,
    quantity: 22
  },
  {
    id: 55,
    name: "Hair Accessories Set",
    category: "Accessories",
    price: 599,
    originalPrice: 999,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRymu1CnuE8BC4Op61Wo6TrGqGfvtuM6gtUuMdXiAmSjA&s=10",
    description: "Complete hair accessories set for all occasions.",
    rating: 4.8,
    reviews: 445,
    inStock: true,
    quantity: 40
  },
  {
    id: 56,
    name: "Wallet Leather",
    category: "Accessories",
    price: 899,
    originalPrice: 1499,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRVqo_w3ZBPhEjALedh4CXJ2JwmAvqI1M-6C4N-lvDUnw&s=10",
    description: "Premium leather wallet with multiple card slots.",
    rating: 4.7,
    reviews: 178,
    inStock: true,
    quantity: 26
  }
];

// ==================== CATEGORIES ====================
const categories = [
  { id: 1, name: "Electronics", icon: "📱" },
  { id: 2, name: "Fashion", icon: "👗" },
  { id: 3, name: "Beauty", icon: "💄" },
  { id: 4, name: "Home Decor", icon: "🏠" },
  { id: 5, name: "Footwear", icon: "👠" },
  { id: 6, name: "Books", icon: "📚" },
  { id: 7, name: "Accessories", icon: "💍" }
];

// ✅ CORRECT WAY FOR BACKEND - USE module.exports (CommonJS)
export { products, categories };